[toolchain]
<<<<<<< Updated upstream
channel = "nightly-2023-06-28"
=======
channel = "nightly-2023-06-15"
>>>>>>> Stashed changes
components = ["rust-std", "rust-src", "rustfmt", "clippy"]
targets = ["x86_64-unknown-linux-gnu", "riscv64gc-unknown-none-elf"]
profile = "minimal"
